"""Report generation API routes."""

from datetime import datetime
from fastapi import APIRouter
from fastapi.responses import PlainTextResponse
from api.database import get_db

router = APIRouter()


@router.get("/reports/weekly", response_class=PlainTextResponse)
async def generate_weekly_report(site: str):
    with get_db() as conn:
        views = conn.execute("SELECT COUNT(*) as count FROM events WHERE site = ? AND event_type = 'pageview' AND timestamp >= datetime('now', '-7 days')", (site,)).fetchone()
        visitors = conn.execute("SELECT COUNT(DISTINCT session_id) as count FROM events WHERE site = ? AND event_type = 'pageview' AND timestamp >= datetime('now', '-7 days')", (site,)).fetchone()
        top_pages = conn.execute("SELECT url, COUNT(*) as views FROM events WHERE site = ? AND event_type = 'pageview' AND timestamp >= datetime('now', '-7 days') GROUP BY url ORDER BY views DESC LIMIT 5", (site,)).fetchall()
        failed = conn.execute("SELECT query, COUNT(*) as count FROM search_queries WHERE site = ? AND results_count = 0 AND timestamp >= datetime('now', '-7 days') GROUP BY query ORDER BY count DESC LIMIT 5", (site,)).fetchall()
        fb = conn.execute("SELECT SUM(CASE WHEN helpful=1 THEN 1 ELSE 0 END) as up, SUM(CASE WHEN helpful=0 THEN 1 ELSE 0 END) as down FROM feedback WHERE site=? AND timestamp >= datetime('now', '-7 days')", (site,)).fetchone()

    report = f"# Documentation Performance Report — Week of {datetime.now().strftime('%B %d, %Y')}\n## {site}\n\n"
    report += "### Key Metrics\n"
    report += f"- Total page views: {views['count'] if views else 0}\n"
    report += f"- Unique visitors: {visitors['count'] if visitors else 0}\n"

    if fb:
        up, down = fb["up"] or 0, fb["down"] or 0
        total = up + down
        report += f"- Feedback: {up} positive, {down} negative ({round((up/total)*100) if total else 0}% positive)\n"

    report += "\n### Top Pages\n"
    for i, p in enumerate(top_pages, 1):
        report += f"{i}. {p['url']} ({p['views']} views)\n"

    report += "\n### Content Gaps (Failed Searches)\n"
    if failed:
        for f_item in failed:
            report += f"- \"{f_item['query']}\" ({f_item['count']} searches)\n"
    else:
        report += "No failed searches detected.\n"

    report += f"\n---\n*Generated by DocPulse on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n"
    return report
